version: 2
workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - untagged-build
  tagged-build:
    jobs:
      - tagged-build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x scripts/tag.sh
            shellcheck -x scripts/install_plugin.sh
  untagged-build:
    docker:
      - image: go:1.21
    steps:
      - checkout
      - run:
          command: make build
          no_output_timeout: 20m
  tagged-build:
    docker:
      - image: go:1.21
    steps:
      - checkout
      - run:
          command: curl -sfL https://goreleaser.com/static/run | bash
          no_output_timeout: 40m
